# Generated by Django 3.2.4 on 2022-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpic', models.ImageField(default='', upload_to='static/certificate/')),
                ('cname', models.CharField(max_length=50)),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20)),
                ('massage', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ppic', models.ImageField(default='', upload_to='static/profile/')),
                ('dec', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpic', models.ImageField(default='', upload_to='static/resume/')),
                ('rdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdate', models.DateField()),
            ],
        ),
    ]
