# Generated by Django 3.2.4 on 2022-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='cdate',
            new_name='rdate',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cname',
            field=models.CharField(max_length=100),
        ),
    ]
